version: "3.7"
services:
  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  react:
    build:
      context: ./frontend
      dockerfile: ../compose/react/Dockerfile
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - django
    command: npm start
